services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dam_inspection_api
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    depends_on:
      - db
    networks:
      - dam_network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - dam_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  dam_network:
    driver: bridge

volumes:
  postgres_data:
